### ISSUE TITLE
Eat your own dog food

### ISSUE THREAD

**Issue by guilhermeblanco** [object-calisthenics/phpcs-calisthenics-rules#1]
When creating phpcs rules, it should also enforced to follow them internally too.
The idea is to finish all 10 rules, then update codebase to meet them.
Roadmap:
- [x] Create all rules (make it work)
- [x] Expand test cases to cover a good chunk of use cases (make it right)
- [ ] Make internal code also follow the rules (make it fast)

That's a good exercise to show people how any code can be turned into compliant OC code.

**Comment by TomasVotruba** [comment]
Resolved via #29
