### ISSUE TITLE
PHP_CodeSniffer 2.0.0 compatibility

### ISSUE THREAD

**Issue by CelineDesign** [object-calisthenics/phpcs-calisthenics-rules#10]
When running phpcs-calisthenics-rules with PHP_CodeSniffer 2.0.0, i've the following error :
Fatal error: Class 'PHP_CodeSniffer_CommentParser_MemberCommentParser' not found in .composer/vendor/object-calisthenics/phpcs-calisthenics-rules/ObjectCalisthenics/PropertyTypePerClassLimitSniff.php on line 328

Phpcs and phpcs-calisthenics-rules installed globally through composer.

**Comment by TomasVotruba** [comment]
Already fixed
