### ISSUE TITLE
Impossible to suppress ObjectCalisthenics.Metrics.MethodPerClassLimit

### ISSUE THREAD

**Issue by kiler129** [object-calisthenics/phpcs-calisthenics-rules#104]
It seems like a standard method of suppression (`@phpcsSuppress ObjectCalisthenics.Metrics.MethodPerClassLimit`) doesn't work when added to the `class`.

Is it a known issue or is there a different method of suppressing that check for a particular class without excluding the whole file? (which in my case is marked for refactoring)

**Comment by TomasVotruba** [comment]
These rules are designed to work with [ECS](https://github.com/symplify/easy-coding-standard), where `@phpSuppress` is not supported.

There you can ignore it like this: https://github.com/symplify/easy-coding-standard#exclude-checkers
