### ISSUE TITLE
Switch is detected as two nesting levels

### ISSUE THREAD

**Issue by Rarst** [object-calisthenics/phpcs-calisthenics-rules#13]
PHP switch statement is being detected as two levels of logic nesting. This seems incorrect, unless the intent is to discourage switch altogether.

**Comment by TomasVotruba** [comment]
Could you send PR with failing test, please? I'll look on that.

**Comment by Rarst** [comment]
Sorry, I am not actively using these sniffs anymore (stopped over version incompatibilities as per other issue you commented on). And as above it wasn't clear what the _intent_ about `switch` is.

**Comment by TomasVotruba** [comment]
Ok, thank you for info. 

Just personal curiosity: what standards do you use now?

**Comment by Rarst** [comment]
Primarily [WordPress CS](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) and [Yoast CS](https://github.com/Yoast/yoastcs) downstream from it.

**Comment by TomasVotruba** [comment]
Thanks for sharing. You use that because of you work with Wordpress or is there something interesting even for non-Wordpress people?

**Comment by Rarst** [comment]
Purely because I work with WordPress, they are specific to it. :)

**Comment by TomasVotruba** [comment]
I see :)
