### ISSUE TITLE
Error when running PHPUnit

### ISSUE THREAD

**Issue by JeroenDeDauw** [object-calisthenics/phpcs-calisthenics-rules#14]
Perhaps I'm missing the obvious here...

Did a git clone, ran `composer install`, then `phpunit`:

RuntimeException: Could not find PHP_CodeSniffer test suite. Did you maybe forget to run composer installation with option "--prefer-source"? in /home/j/workspace/phpcs-calisthenics-rules/bootstrap.php on line 68

phpunit --version
PHPUnit 4.2.2 by Sebastian Bergmann.

commit 51b3b42033530ee32e6dbe114eb1ade5f94fab92

**Comment by TomasVotruba** [comment]
Probably fixed already

**Comment by JeroenDeDauw** [comment]
I just confirmed it is... closing with "probably fixed" is kinda weird

**Comment by TomasVotruba** [comment]
Thank you. 
Well, I tried the use case and it worked for ME in MY environment. It always about probability.
