### ISSUE TITLE
Error when run composer to install dependencies

### ISSUE THREAD

**Issue by malukenho** [object-calisthenics/phpcs-calisthenics-rules#16]
I have in my `composer.json` file:

```json
"require-dev": {
        "phpunit/phpunit": "4.*",
        "squizlabs/php_codesniffer": "dev-master",
        "object-calisthenics/phpcs-calisthenics-rules": "dev-master"
}
```
Raise the follow error

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for squizlabs/php_codesniffer dev-master -> satisfiable by squizlabs/php_codesniffer[dev-master].
    - object-calisthenics/phpcs-calisthenics-rules dev-master requires squizlabs/php_codesniffer ~1.5 -> satisfiable by squizlabs/php_codesniffer[1.5.x-dev].
    - Can only install one of: squizlabs/php_codesniffer[dev-master, 1.5.x-dev].
    - Installation request for object-calisthenics/phpcs-calisthenics-rules dev-master -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[dev-master]
```

When I replace version of php_codesniffer to `~1.5` its works.

**Comment by malukenho** [comment]
ping @guilhermeblanco

**Comment by harikt** [comment]
@malukenho `object-calisthenics/phpcs-calisthenics-rules` already requiring `squizlabs/php_codesniffer` , may be you don't need to require `squizlabs/php_codesniffer`  dev-master ?

If you still need, it seems you could write something like `"squizlabs/php_codesniffer":"dev-master as 1.5.x-dev"`  . I am still not sure whether the syntax is correct. Anyway you need to make alias I think.

**Comment by malukenho** [comment]
@harikt I will try this solution. Thanks!

**Comment by harikt** [comment]
@malukenho sure. Have a look at https://getcomposer.org/doc/articles/aliases.md .

**Comment by malukenho** [comment]
It's works :beers:

**Comment by TomasVotruba** [comment]
Works just fine now with tagged version
