### ISSUE TITLE
More specifcly about types on docBlocks

### ISSUE THREAD

**Issue by malukenho** [object-calisthenics/phpcs-calisthenics-rules#17]
I want to be more specific about types in my docBlock, for example:

``` php
/**
 * @param string[] $bar
 */
public function Foo(array $bar) {
     // ...
}
```

But it's actually raise a error on CS validation.

`Expected type hint "string[]"; found "array" for $bat at position 1`

**Comment by guilhermeblanco** [comment]
@malukenho Using `string[]` confuses almost every single IDE I know.
I noticed that PHPStorm uses something like `array<string>` to type check things, but can't confirm at the moment.

**Comment by Ocramius** [comment]
I use `string[]` reliably, and it's correctly detected by PHPDocumentor as well.
Should just be allowed, as it's the most common way to annotate arrays.

**Comment by TomasVotruba** [comment]
This works fine now. Not sure even if that was in scope of this cs.
