### ISSUE TITLE
The project only works on phpcs 1.*

### ISSUE THREAD

**Issue by jeanCarloMachado** [object-calisthenics/phpcs-calisthenics-rules#18]
If I use 2.\* versions I got this error: 
`Fatal error: Class 'PHP_CodeSniffer_CommentParser_MemberCommentParser' not found` 

It would be nice to upgrade the version or at least to update composer.json with the real requirements of the project.

**Comment by AngeIII** [comment]
+1

**Comment by TomasVotruba** [comment]
Could you send PR?

**Comment by TomasVotruba** [comment]
Already bumped to 2.*
