### ISSUE TITLE
Rule 2 misinterpreted with switch?

### ISSUE THREAD

**Issue by roukmoute** [object-calisthenics/phpcs-calisthenics-rules#36]
Hello!

I've just seen when a method contains a switch/case statement, for the interpreter there is two indentations level.
I understand the idea, but in fact there is only one level, no ?

Could we improve this rule?

See you ;)

**Comment by roukmoute** [comment]
@TomasVotruba

**Comment by TomasVotruba** [comment]
Hi, I didn't create this rule, so I'm not sure what the intention is.

What exactly do you suggest? Could you past BEFORE and AFTER code?

Thank you :)

Thanks for ping, I didn't notice it on first time.

**Comment by roukmoute** [comment]
With this simple code :), I have this message:

`Only one indentation level per function/method. Found 2 levels.`

```php
public function foo($bar = '123')
{
    switch ($bar) {
        case '123':
            echo 'test';
            break;
        default:
            break;
    }
}
```

**Comment by TomasVotruba** [comment]
I see the problem here.

Could you send the PR please?

**Comment by roukmoute** [comment]
Yep of course I will do that :)

It was to be sure that it was a mistake or if it was normal.
