### ISSUE TITLE
About MethodPerClassLimitSniff

### ISSUE THREAD

**Issue by gmponos** [object-calisthenics/phpcs-calisthenics-rules#38]
I was trying to make some research about Object Calisthenics

So about this sniff I was wondering. 
- Should the __constructor be included?
- Should the private/protected methods be included?
- Should any magic methods be included like `__toString()`?

**Comment by TomasVotruba** [comment]
Hi @gmponos, thanks for the research.

I think all methods should be included, apart system interfaces - cause they are hard limited.

Maybe this limit could be configurable, so it would suite particular level of project.

**Comment by TomasVotruba** [comment]
Closing due to timeout
