### ISSUE TITLE
Only one level ? And what abouht try catch ?

### ISSUE THREAD

**Issue by oxman** [object-calisthenics/phpcs-calisthenics-rules#39]
```php

public function addLinkBetweenOauthClientAndUserFromIds($oauthClientId, $userId)
    {
        try {
            $oauthClient = $this->oauthClientRepository->get($oauthClientId);
            if ($oauthClient === null) {
                return false;
            }
            $user = $this->userRepository->get($userId);
            if ($user === null) {
                return false;
            }
            return $this->addLinkBetweenOauthClientAndUser($oauthClient, $user);
        } catch (Exception $exception) {
            $this->logger->error(
                'Can\'t link from their ids oauth client: ' . $oauthClient->getId() . ' and user: ' . $user->getId()
                . '. Error: ' .$exception->getMessage()
            );
            return false;
        }
    }
```

With a code like that, i mean code in a try catch, only one level seems too restrictive no ?
So maybe an exception of two level when the first or the second is a try catch ?

**Comment by TomasVotruba** [comment]
Hi @oxman, thanks for the feedback.

Your code could be refactored neatly to this:

```php
public function addLinkBetweenOauthClientAndUserFromIds($oauthClientId, $userId)
{
    try {
        return $this->processOauthClientAndUser(...);
    } catch (Exception $exception) {
        $this->logger->error(...);
        return false;
   }
}
```

The goal if this rule is to keep code as much as readable, so making exception for nesting might allow to write more and more nested code.


On the other hand, do you imagine any other situation to make exception for?

Would you prepare a PR for this?

**Comment by oxman** [comment]
Ofc i can refactor like that. But this method will be very specialized and only used in this case. So i think we shouldn't do that.

**Comment by TomasVotruba** [comment]
On the other hand, do you imagine any other situation to make exception for?

Would you prepare a PR for this?

**Comment by oxman** [comment]
I said only one level exception for "try catch", nothing else.
So the max level will be 2 (instead of 1) and only if one of the both level is a try catch.

I don't want make a PR about this, for the moment i only want your opinion.

**Comment by TomasVotruba** [comment]
I agree.

**Comment by TomasVotruba** [comment]
Duplicate to #40
