### ISSUE TITLE
Question about Fluent Interfaces

### ISSUE THREAD

**Issue by UFOMelkor** [object-calisthenics/phpcs-calisthenics-rules#41]
Hi,

is there any way to get rid of the `Only one object operator per line.` errors when using the `Doctrine\DBAL\Query\QueryBuilder`?

**Comment by TomasVotruba** [comment]
Hi, I think there would have to be added an exception for these objects.

Would you be able to add one in PR?

**Comment by UFOMelkor** [comment]
Only idea I have that would really work is to identify the return type of each method call and compare it with the calling one, but this sounds like a horrible piece of work …
Do you have any other idea or would this be the way to go?

**Comment by TomasVotruba** [comment]
Maybe skip this rule for specific strings, like: `createQueryBuilder`

**Comment by UFOMelkor** [comment]
Ok, I'll try to prepare a PR in the next days :-)

**Comment by TomasVotruba** [comment]
Awesome, thank you for your time!

**Comment by TomasVotruba** [comment]
Clsoed via #43
