### ISSUE TITLE
Missing ObjectCalisthenics/Sniffs/Files/ClassElementLengthSniff.php

### ISSUE THREAD

**Issue by syrm** [object-calisthenics/phpcs-calisthenics-rules#60]
Referenced sniff "ObjectCalisthenics.Files.ClassElementLength" does not exist

**Comment by TomasVotruba** [comment]
Where exactly?

**Comment by syrm** [comment]
Where ? Everywhere !

./bin/phpcs --standard=vendor/object-calisthenics/phpcs-calisthenics-rules/src/ObjectCalisthenics
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Referenced sniff "ObjectCalisthenics.Files.ClassElementLength" does not exist in /home/srm/sync/blackprism2/couchbase-odm/vendor/squizlabs/php_codesniffer/src/Ruleset.php:762

**Comment by TomasVotruba** [comment]
Oh, I see. This is fixed in PR: https://github.com/object-calisthenics/phpcs-calisthenics-rules/pull/59

This sniff was renamed and extended.

I'll try to finish it today.

**Comment by syrm** [comment]
You should test before each push ;)

**Comment by TomasVotruba** [comment]
It's just in the docs

**Comment by syrm** [comment]
Look my second answer.

**Comment by TomasVotruba** [comment]
Good idea. Could you send PR with that to current master?

**Comment by syrm** [comment]
With what ?

**Comment by TomasVotruba** [comment]
With that test you mentioned. "Look my second answer."

**Comment by syrm** [comment]
When you edit the code you never test it ? You need a PR to tell you "before commit test your code" ?

**Comment by TomasVotruba** [comment]
What? How is that relevant to Travis? No, I mean these lines

```
./bin/phpcs --standard=vendor/object-calisthenics/phpcs-calisthenics-rules/src/ObjectCalisthenics
```

**Comment by syrm** [comment]
I didn't say anything about travis.

**Comment by TomasVotruba** [comment]
Nevermind, it's fixed in the PR.
