### ISSUE TITLE
Release v3.0?

### ISSUE THREAD

**Issue by UFOMelkor** [object-calisthenics/phpcs-calisthenics-rules#61]
Now that the [new version of PHP CodeSniffer has been released](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0) is there anything that prevents a v3.0 stable release?

**Comment by TomasVotruba** [comment]
Horray! :tada: :tada: :tada:  I was waiting for 8 months for this.

How did you noticed that? I have [an email notification](https://libraries.io/packagist/squizlabs%2Fphp_codesniffer) for this.

To your question: Nope, that's all I was waiting for.

**Comment by TomasVotruba** [comment]
Well, I noticed we have to wait for slevomat/coding-standard to be released for CS 3 as well: https://github.com/slevomat/coding-standard/pull/151

Also, could you check and proofread README if there is everything nice and clear?

**Comment by TomasVotruba** [comment]
After 8 months of collective work, I'm proud to announce the job is done! 

https://github.com/object-calisthenics/phpcs-calisthenics-rules/releases/tag/v3.0.0

I'd be happy if you tests it and let me know, how it works. Enjoy

**Comment by UFOMelkor** [comment]
Thanks for your hard work :+1: 
Found one missing dependency (#66), everything else seems to work really great :smiley:
