### ISSUE TITLE
Request: 2.* release with phpcodesniffer-standard

### ISSUE THREAD

**Issue by GaryJones** [object-calisthenics/phpcs-calisthenics-rules#69]
I've got a situation where the production server has PHP 7.0 (limited to Object Calisthenics 2.*), but I want to use a Composer plugin for registering the PHP CodeSniffer standards in my project (requires OC define `phpcodesniffer-standard` value in `composer.json`).

Would it be possible to please add a 2.0.1 release that adds the required key to `composer.json`, without bumping the minimum version of PHP?

**Comment by TomasVotruba** [comment]
I personally don't have time for taking care of this, but why not.
Could you send PR for that? I'll do the tagging then.

**Comment by GaryJones** [comment]
@TomasVotruba,

Can you please make a branch for `v2.0.0`? Just having a tag isn't apparently enough for GitHub to allow me to create a pull request.

**Comment by TomasVotruba** [comment]
Sure. Which commit should I use?

**Comment by GaryJones** [comment]
The [`v2.0.0` tag](https://github.com/object-calisthenics/phpcs-calisthenics-rules/releases/tag/v2.0.0) is against [this commit](https://github.com/object-calisthenics/phpcs-calisthenics-rules/commit/3c5a9b28709a9f7d941c438cb2ad255712fae87e).

**Comment by TomasVotruba** [comment]
Thank. There you go: https://github.com/object-calisthenics/phpcs-calisthenics-rules/tree/2.0

Is that what you needed?

**Comment by TomasVotruba** [comment]
Closed by #70
