### ISSUE TITLE
Class 'Nette\Utils\Strings' not found possible problem with phpcs 3.2.3 ?

### ISSUE THREAD

**Issue by widoz** [object-calisthenics/phpcs-calisthenics-rules#83]
I always get this when trying to run `phpcs`.

I read the code and seems everything ok but the class `Strings` doesn't exists.

Error: Class 'Nette\Utils\Strings' not found in /Users/user/Sites/sniffs/phpcs-calisthenics-rules/src/ObjectCalisthenics/Helper/Naming.php on line 43

Call Stack:
    0.0006     392504   1. {main}() /usr/local/bin/phpcs.phar:0
    0.0057     743384   2. PHP_CodeSniffer\Runner->runPHPCS() /usr/local/bin/phpcs.phar:6
    0.1221    8372216   3. PHP_CodeSniffer\Runner->run() phar:///usr/local/bin/phpcs.phar/src/Runner.php:2
    0.1291    8898144   4. PHP_CodeSniffer\Runner->processFile() phar:///usr/local/bin/phpcs.phar/src/Runner.php:2
    0.1291    8898144   5. PHP_CodeSniffer\Files\LocalFile->process() phar:///usr/local/bin/phpcs.phar/src/Runner.php:2
    0.1291    8898144   6. PHP_CodeSniffer\Files\LocalFile->process() phar:///usr/local/bin/phpcs.phar/src/Files/LocalFile.php:2
    0.1516    9349616   7. ObjectCalisthenics\Sniffs\NamingConventions\ElementNameMinimalLengthSniff->process() phar:///usr/local/bin/phpcs.phar/src/Files/File.php:2
    0.1521    9356928   8. ObjectCalisthenics\Helper\Naming::getElementName() /Users/user/Sites/sniffs/phpcs-calisthenics-rules/src/ObjectCalisthenics/Sniffs/NamingConventions/ElementNameMinimalLengthSniff.php:39

**Comment by TomasVotruba** [comment]
Hi, is `Nette\Utils\Strings` class autolaoded?

Is `phpcs` skipping the `vendor/autolaod.php`?

**Comment by widoz** [comment]
Hi @TomasVotruba it's me again, 

Sorry for the double reply but I guess I found the problem. I don't know exactly where could be in terms of line of codes but using the latest version of phpcs seems causing the issue. I switched to the latest version for 3.2.x and phpcs is able to work correctly without problems.

**Comment by TomasVotruba** [comment]
Hey, 

that's great to hear! I tried to reproduce the issue and find myself stuck with autoloading problems. That's why I prefer [ECS](https://github.com/symplify/easyCodingStandard/), where these problems doesn't exist.

I'm glad it works :+1:
