### ISSUE TITLE
packagist.org don't contain v3.5.1

### ISSUE THREAD

**Issue by nunomaduro** [object-calisthenics/phpcs-calisthenics-rules#90]
Seems that something is wrong on the packages web hook as it don't contain the version v3.5.1: https://packagist.org/packages/object-calisthenics/phpcs-calisthenics-rules.

Can you trigger a manual update? Or maybe fix this?

Thanks!

**Comment by TomasVotruba** [comment]
I'm not the maintainer there, @guilhermeblanco

**Comment by guilhermeblanco** [comment]
I've ran an update, but I need to know what's your packagist user @TomasVotruba... so I cna add you there =)

**Comment by TomasVotruba** [comment]
https://packagist.org/?query=tomasvotruba

**Comment by nunomaduro** [comment]
This issue seems fixed. Thanks!

**Comment by guilhermeblanco** [comment]
=( tomasvotruba => User not found!

![Screen Shot 2019-05-16 at 4 47 02 PM](https://user-images.githubusercontent.com/208883/57886026-4c786a00-77fa-11e9-8cd0-870fc7b17186.png)

**Comment by TomasVotruba** [comment]
Damn!

This one: https://packagist.org/users/Tom%C3%A1%C5%A1%20Votruba/

**Comment by guilhermeblanco** [comment]
\o/ Worked! You're now added as a co-maintainer of the package

**Comment by TomasVotruba** [comment]
Thank you :+1:
