### ISSUE TITLE
Unexpected value on getStructureLengthInLines

### ISSUE THREAD

**Issue by Malows** [object-calisthenics/phpcs-calisthenics-rules#91]
On [**Helper/Structure/StructureMetrics::getStructureLengthInLines**.](https://github.com/object-calisthenics/phpcs-calisthenics-rules/blob/master/src/ObjectCalisthenics/Helper/Structure/StructureMetrics.php#L22)
The function retrieves the difference between the opening and the ending position of the function body. But empty lines should count as code? Why not avoid them on the count?

**Comment by TomasVotruba** [comment]
Good point. How would you improve it?

**Comment by TomasVotruba** [comment]
Closing for lack of feedback
