### ISSUE TITLE
requires slevomat/coding-standard ^5.0.4 but it has already installed 6.0.1

### ISSUE THREAD

**Issue by harrisdt15f** [object-calisthenics/phpcs-calisthenics-rules#95]
Problem 1
     - object-calisthenics/phpcs-calisthenics-rules v3.6.0 requires slevomat/coding-standard ^5.0.4 -> satisfiable by slevomat/coding-standard[5.0.4] but these conflict with your requirements or minimum-stability.
     - object-calisthenics/phpcs-calisthenics-rules v3.5.1 requires slevomat/coding-standard ^5.0 -> satisfiable by slevomat/coding-standard[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4] but these conflict with your requirements or minimum-stability.
     - object-calisthenics/phpcs-calisthenics-rules v3.5.0 requires slevomat/coding-standard ^5.0 -> satisfiable by slevomat/coding-standard[5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4] but these conflict with your requirements or minimum-stability.
     - object-calisthenics/phpcs-calisthenics-rules v3.6.0 requires slevomat/coding-standard ^5.0.4 -> satisfiable by slevomat/coding-standard[5.0.4] but these conflict with your requirements or minimum-stability.
     - Installation request for object-calisthenics/phpcs-calisthenics-rules ^3.5 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.5.0, v3.5.1, v3.6.0].

**Comment by TomasVotruba** [comment]
The composer.json needs to be updated

**Comment by harrisdt15f** [comment]
here is my config inside composer.json and I also clear the composer.lock before update but it still cannot install please help
"require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.5.0",
        "facade/ignition": "^1.11",
        "friendsofphp/php-cs-fixer": "^2.16",
        "fzaninotto/faker": "^1.8",
        "mockery/mockery": "^1.2",
        "nunomaduro/collision": "^3.0",
        "nunomaduro/larastan": "^0.4.3",
        "slevomat/coding-standard": "^6.0",
        "object-calisthenics/phpcs-calisthenics-rules": "^3.6",
        "phpcompatibility/php-compatibility": "^9.3",
        "phpunit/phpunit": "^8.4",
        "sirbrillig/phpcs-import-detection": "^1.2",
        "squizlabs/php_codesniffer": "^3.5"
    },

**Comment by harrisdt15f** [comment]
Using version ^3.6 for object-calisthenics/phpcs-calisthenics-rules
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for object-calisthenics/phpcs-calisthenics-rules ^3.6 -> satisfiable by object-calisthenics/phpcs-calisthenics-rules[v3.6.0].
    - object-calisthenics/phpcs-calisthenics-rules v3.6.0 requires slevomat/coding-standard ^5.0.4 -> satisfiable by slevomat/coding-standard[5.0.4] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

**Comment by TomasVotruba** [comment]
It must be allowed here in `composer.json`, feel free to send PR

**Comment by harrisdt15f** [comment]
Thank you
